### ISSUE TITLE
Use with apollo 2

### ISSUE THREAD

**Issue by perrosnk** [kanzitelli/react-native-navigation-mobx-boilerplate#3]
First of all, thank you very much for this boilerplate.
Have you tried using RNN and mobx with Apollo 2 (react-apollo)? 
There is a discussion here: https://github.com/wix/react-native-navigation/issues/1883, but I think they are not using mobx, and I am having a very difficult time making all 3 work together. Any ideas?

**Comment by kanzitelli** [comment]
Hello, @perrosnk!

Thank you for your words! 
I have stopped working with RN about a half year ago and never used it with Apollo 2. But I have read that thread about integrating Apollo 2 and checked some code in [RNN repo](https://github.com/wix/react-native-navigation/blob/17701133211d914f0d00089f0d65cc873030e980/src/Navigation.js#L60-L91) and [Apollo 2 repos](https://github.com/apollographql/react-apollo/blob/master/src/ApolloProvider.tsx) and I have come up with the idea that might help you: what if you create another store, let's say `ApolloClient`, configure your client there and then it will be available in `/src/utils/MobxRnnProvider.js` and you will have an access to your store where you can get configured client from through `this.props.store['ApolloClient']`. 

And wrap it all with `ApolloProvider` from `react-apollo`:
```
render() {
    return(
      <ApolloProvider client={this.props.store['ApolloClient'].client}>
        { Children.only(this.props.children) }
      </ApolloProvider>
    )
  }
```
_add this code in the end of `/src/utils/MobxRnnProvider.js`_
[gist](https://gist.github.com/kanzitelli/c407a1a8c64bd63d06badd71eadd76e8)

I am not sure if it's going to work but at least it might lead you to the actual solution. Let me know how it goes 🙃

**Comment by perrosnk** [comment]
@kanzitelli Honestly, there is no way to thank you as much as I want! I have spent so many hours trying to find a way, and you really saved my day!!
